### ISSUE TITLE
circularList with two elements creates bad transform

### ISSUE THREAD

**Issue by jrguiguy** [srguiwiz/adj-js#15]
see this http://jsbin.com/newame/edit?html,output

one rectangle translates with a huge number

probably edge case with only one item on circle

**Comment by srguiwiz** [comment]
Fixed in release 5.0.1.

In [your example](http://jsbin.com/newame/edit?html,output) you should update the script src to today's `/d1j1oqlh0aayfqb/adj-v5.0.1.js` .

Thank you.
