### ISSUE TITLE
SVGPathSeg removed in Chrome 48

### ISSUE THREAD

**Issue by jrguiguy** [srguiwiz/adj-js#16]
Attempting to run test-adj-ex-006-connection.svg will result in a warning in the console stating that SVGPathSeg will be removed in Chrome 48. Discussion here: 

https://groups.google.com/a/chromium.org/forum/?fromgroups#!topic/blink-dev/EDC3cBg9mCU

**Comment by srguiwiz** [comment]
Thank you for reporting.  A workaround has been coded, still going to clean it up before committing.

**Comment by srguiwiz** [comment]
For the record, we had actually looked at https://code.google.com/p/chromium/issues/detail?id=539385 first when developing the fix.

**Comment by srguiwiz** [comment]
Fixed in version 5.2.0.
